# Generated by Django 3.2.12 on 2022-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_name_der_praxis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strasse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strasse_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
