# Generated by Django 3.2.12 on 2022-03-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220325_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='strasse',
            field=models.CharField(max_length=30),
        ),
    ]
