# Generated by Django 3.2.12 on 2022-04-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_arzt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='anmerkungen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groese_praxis',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='raume',
        ),
    ]
