# Generated by Django 3.2.12 on 2022-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220410_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anmerkungen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ansprechpartner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='arzt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groese_praxis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mitarbeiter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='raume',
            field=models.IntegerField(null=True),
        ),
    ]
